edition = "2021"
match_block_trailing_comma = true
use_field_init_shorthand = true
use_small_heuristics = "Max"
use_try_shorthand = true

# nightly/unstable features
group_imports = "StdExternalCrate"
imports_granularity = "Module"
imports_layout = "HorizontalVertical"
normalize_comments = true
overflow_delimited_expr = true
